---
title: "derivatives"
format: html
editor_options: 
  chunk_output_type: console
---

```{r}
library(tidyverse)
library(palmerpenguins)
```

```{r}
# Find the slope of f(x) = x^2 at x = 3
ct <- function(x){
  x^2
}

# find deriv of C(t) ----
dc_dt <- D(expr = expression(x^2), name="x")
dc_dt

# store the deriv as a function ----
dc_dt_fun <- function(t) {
  2*x
}
x=3
dc_dt_fun(x)
```

```{r}
# Find the slope of P(a) = 2(3a+2)^4 - 5 at a=1.2
cP <- function(a){
  2* (3*a+2)^4 -5
}

# find deriv of C(t) ----
dcP_dt <- D(expr = expression(2* (3*a+2)^4 -5), name="a")
dcP_dt

# store the deriv as a function ----
dc_dt_fun <- function(a) {
  2 * (4 * (3 * (3 * a + 2)^3))
}
a<-1.2
dc_dt_fun(a)
```

```{r}
ggplot(data = penguins, aes(x = bill_depth_mm, y = bill_length_mm)) +
  geom_point(aes(color = species)) +
  scale_color_manual(values = c("darkorange","yellow","red")) +
  labs(y = "Bill Length (mm)",
       x = "Bill Depth (mm)",
       title = "Palmer penguin bill measurements",
       subtitle = "Palmer Archipelago, Antarctice (2007 - 2009)",
       caption = "Collected by Dr. Kristen Gorman and colleagues at Palmer Station LTER") +
  facet_wrap(~island) +
  theme_minimal()
```

```{r}
ggplot(data = penguins, aes(x = species, y = flipper_length_mm)) +
  geom_jitter(aes(color = species)) +
  scale_color_manual(values = c("darkorange","yellow","red")) +
  labs(x = "Species",
       y = "Flipper Length (mm)",
       title = "Palmer penguin Flipper Length by Species",
       subtitle = "Palmer Archipelago, Antarctice (2007 - 2009)",
       caption = "Collected by Dr. Kristen Gorman and colleagues at Palmer Station LTER") +
  facet_wrap(~island) +
  theme_minimal()
```
